// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFBDPZwVCvVXbYu2h2x3FeOmfW4UlClF8',
    appId: '1:361421917219:web:34ca5112fe07e5d9dbb596',
    messagingSenderId: '361421917219',
    projectId: 'food-admin-panel-9db43',
    authDomain: 'food-admin-panel-9db43.firebaseapp.com',
    storageBucket: 'food-admin-panel-9db43.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE5SzhkOLlqlf9uKaZ9-AMxfGBEc-SHy4',
    appId: '1:361421917219:android:970dc9a1e7571c2ddbb596',
    messagingSenderId: '361421917219',
    projectId: 'food-admin-panel-9db43',
    storageBucket: 'food-admin-panel-9db43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQWQ7b4CoB3W07ZXKhFXPt4ZqDPuqyPFs',
    appId: '1:361421917219:ios:dd83d6bac52d4915dbb596',
    messagingSenderId: '361421917219',
    projectId: 'food-admin-panel-9db43',
    storageBucket: 'food-admin-panel-9db43.firebasestorage.app',
    iosBundleId: 'com.example.foodAdminPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFBDPZwVCvVXbYu2h2x3FeOmfW4UlClF8',
    appId: '1:361421917219:web:ec4db9b57577cb20dbb596',
    messagingSenderId: '361421917219',
    projectId: 'food-admin-panel-9db43',
    authDomain: 'food-admin-panel-9db43.firebaseapp.com',
    storageBucket: 'food-admin-panel-9db43.firebasestorage.app',
  );
}
